[acoustics]
sr = 16000
n_fft = 512
win_length = 512
hop_length = 256


[inferencer]
path = "inferencer.Inferencer"
type = "full_band_crm_mask"

[inferencer.args]
n_neighbor = 15


[dataset]
path = "FullSubNet.recipes.dns_interspeech_2020.dataset_inference.Dataset"

[dataset.args]
dataset_dir_list = [
#        "~/Datasets/DNS-Challenge-INTERSPEECH/datasets/test_set/synthetic/with_reverb/noisy",
        "~/Datasets/DNS-Challenge-INTERSPEECH/datasets/test_set/synthetic/no_reverb/noisy",
#    "/apdcephfs/share_976139/xianghao/Datasets_share_976139/DNS-INTERSPEECH-2020/datasets/test_set/synthetic/no_reverb/noisy"
    # ~/Experiments/fullsubnet_best_model_58epochs.tar
]
sr = 16000


[model]
path = "FullSubNet.recipes.dns_interspeech_2020.fullsubnet.model.Model"

[model.args]
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_num_neighbors = 0
sb_num_neighbors = 15
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2

