[meta]
save_dir = "~/Experiments/FullSubNet/"
description = "This is a description of FullSubNet experiment."
seed = 0  # set random seed for random, numpy, pytorch-gpu and pytorch-cpu
use_amp = true
cudnn_enable = false

[acoustics]
n_fft = 512
win_length = 512
sr = 16000
hop_length = 256


[loss_function]
name = "mse_loss"
[loss_function.args]


[optimizer]
lr = 0.001
beta1 = 0.9
beta2 = 0.999


[train_dataset]
path = "dataset_train.Dataset"
[train_dataset.args]
clean_dataset = "~/Datasets/DNS-Challenge-INTERSPEECH/datasets/clean_0.6.txt"
clean_dataset_limit = false
clean_dataset_offset = 0
noise_dataset = "~/Datasets/DNS-Challenge-INTERSPEECH/datasets/noise.txt"
noise_dataset_limit = false
noise_dataset_offset = 0
num_workers = 36
pre_load_clean_dataset = false
pre_load_noise = false
pre_load_rir = false
reverb_proportion = 0.75
rir_dataset = "~/Datasets/DNS-Challenge-INTERSPEECH/datasets/rir.txt"
rir_dataset_limit = false
rir_dataset_offset = 0
silence_length = 0.2
snr_range = [-5, 20]
sr = 16000
sub_sample_length = 3.072
target_dB_FS = -25
target_dB_FS_floating_value = 10


[train_dataset.dataloader]
batch_size = 48
num_workers = 48
drop_last = true
pin_memory = false


[validation_dataset]
path = "dataset_validation.Dataset"
[validation_dataset.args]
dataset_dir_list = [
    "~/Datasets/DNS-Challenge-INTERSPEECH/datasets/test_set/synthetic/with_reverb/",
    "~/Datasets/DNS-Challenge-INTERSPEECH/datasets/test_set/synthetic/no_reverb/"
]
sr = 16000


[model]
path = "fullsubnet.model.Model"

[model.args]
sb_num_neighbors = 15
fb_num_neighbors = 0
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "cumulative_laplace_norm"
num_groups_in_drop_band = 2


[trainer]
path = "trainer.Trainer"
[trainer.train]
clip_grad_norm_value = 10
epochs = 9999
save_checkpoint_interval = 2
[trainer.validation]
save_max_metric_score = true
validation_interval = 2
[trainer.visualization]
metrics = ["WB_PESQ", "NB_PESQ", "STOI", "SI_SDR"]
n_samples = 10
num_workers = 36
